apiVersion: v1
kind: Secret
metadata:
  name: oxygencs-secret
  namespace: grp01eq8-namespace
type: Opaque
data: # base64 encoded
  TOKEN: MWZhNGFiOTNlNjZlZmI3MzVhZTI=
  DOCKER_TOKEN: ZGNrcl9wYXRfSlJGY3B4d1g1dWt3VUlqN3hCODduUmdCQmRF
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXIwMWVxODpiZDY5NXVUbkE3alVRUXRQQDE1Ny4yMzAuNjkuMTEzL2RiMDFlcTg=
  T_MAX: MjU=  # MjY=/(Old) ============= 25(New)
  T_MIN: MjA= # MTg=(Old) ============= 20(New)
  ENCRYPTION_KEY: NTQ2ODY5NzM0YzYxNjI1Mzc1NjM2Yg==
  ENCRYPTION_IV: OGQ3NGI4NWM0YWYzYTdmZGM4ZjYxYWUzNDIwMWZkNzk=